name: release-crates

permissions:
  pull-requests: write
  contents: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  check:
    name: check / find-pending-releases
    runs-on: ubuntu-latest
    outputs:
      crates_to_publish: ${{ steps.check_crates.outputs.crates_to_publish }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: setup rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1
        with:
          cache: false
      - name: Run release-crates-check.sh
        id: check_crates
        run: |
          chmod +x ./.github/release-crates-check.sh
          ./.github/release-crates-check.sh

  publish-crates:
    name: publish / crates
    runs-on: ubuntu-latest
    needs:
      - check
    env:
      CRATES_PUBLISH_JSON: ${{ needs.check.outputs.crates_to_publish }}
      PUBLISH_CONFIG_CRATE: ${{ contains(needs.check.outputs.crates_to_publish, '"hive-router-config"') }}
      PUBLISH_INTERNAL_CRATE: ${{ contains(needs.check.outputs.crates_to_publish, '"hive-router-internal"') }}
      PUBLISH_QUERY_PLANNER_CRATE: ${{ contains(needs.check.outputs.crates_to_publish, '"hive-router-query-planner"') }}
      PUBLISH_EXECUTOR_CRATE: ${{ contains(needs.check.outputs.crates_to_publish, '"hive-router-plan-executor"') }}
      PUBLISH_ROUTER_CRATE: ${{ contains(needs.check.outputs.crates_to_publish, '"hive-router"') }}
      PUBLISH_GRAPHQL_TOOLS_CRATE: ${{ contains(needs.check.outputs.crates_to_publish, '"graphql-tools"') }}
      PUBLISH_CONSOLE_SDK_CRATE: ${{ contains(needs.check.outputs.crates_to_publish, '"hive-console-sdk"') }}
      PUBLISH_HIVE_APOLLO_ROUTER_PLUGIN: ${{ contains(needs.check.outputs.crates_to_publish, '"hive-apollo-router-plugin"') }}
    if: ${{ github.repository_owner == 'graphql-hive' && needs.check.outputs.crates_to_publish != '{}' }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: setup rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1
        with:
          cache: false

      - name: authenticate with crates.io
        uses: rust-lang/crates-io-auth-action@v1.0.4
        id: auth

      - name: publish graphql-tools lib
        if: env.PUBLISH_GRAPHQL_TOOLS_CRATE == 'true'
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          cargo publish --manifest-path ${{ fromJson(needs.check.outputs.crates_to_publish).graphql-tools }}

      - name: publish hive-console-sdk lib
        if: env.PUBLISH_CONSOLE_SDK_CRATE == 'true'
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          cargo publish --manifest-path ${{ fromJson(needs.check.outputs.crates_to_publish).hive-console-sdk }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        if: env.PUBLISH_HIVE_APOLLO_ROUTER_PLUGIN == 'true'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: publish hive-apollo-router-plugin lib
        if: env.PUBLISH_HIVE_APOLLO_ROUTER_PLUGIN == 'true'
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          cargo publish --manifest-path ${{ fromJson(needs.check.outputs.crates_to_publish).hive-apollo-router-plugin }}

      - name: publish config lib
        if: env.PUBLISH_CONFIG_CRATE == 'true'
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          cargo publish --manifest-path ${{ fromJson(needs.check.outputs.crates_to_publish).hive-router-config }}

      - name: publish internal lib
        if: env.PUBLISH_INTERNAL_CRATE == 'true'
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          cargo publish --manifest-path ${{ fromJson(needs.check.outputs.crates_to_publish).hive-router-internal }}

      - name: publish query-planner lib
        if: env.PUBLISH_QUERY_PLANNER_CRATE == 'true'
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          cargo publish --manifest-path ${{ fromJson(needs.check.outputs.crates_to_publish).hive-router-query-planner }}

      - name: publish executor lib
        if: env.PUBLISH_EXECUTOR_CRATE == 'true'
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          cargo publish --manifest-path ${{ fromJson(needs.check.outputs.crates_to_publish).hive-router-plan-executor }}

      - name: publish router lib
        if: env.PUBLISH_ROUTER_CRATE == 'true'
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          cargo publish --manifest-path ${{ fromJson(needs.check.outputs.crates_to_publish).hive-router }}
